def obfuscate(string):
    for i in string:
        if i == "a":
            string = string.replace("a", "日")
        elif i == "A":
            string = string.replace("A", "一")
        elif i == "b":
            string = string.replace("b", "大")
        elif i == "B":
            string = string.replace("B", "年")
        elif i == "c":
            string = string.replace("c", "中")
        elif i == "C":
            string = string.replace("C", "会")
        elif i == "d":
            string = string.replace("d", "人")
        elif i == "D":
            string = string.replace("D", "本")
        elif i == "e":
            string = string.replace("e", "月")
        elif i == "E":
            string = string.replace("E", "長")
        elif i == "f":
            string = string.replace("f", "国")
        elif i == "F":
            string = string.replace("F", "出")
        elif i == "g":
            string = string.replace("g", "上")
        elif i == "G":
            string = string.replace("G", "十")
        elif i == "h":
            string = string.replace("h", "生")
        elif i == "H":
            string = string.replace("H", "子")
        elif i == "i":
            string = string.replace("i", "分")
        elif i == "I":
            string = string.replace("I", "東")
        elif i == "j":
            string = string.replace("j", "三")
        elif i == "J":
            string = string.replace("J", "行")
        elif i == "k":
            string = string.replace("k", "同")
        elif i == "K":
            string = string.replace("K", "今")
        elif i == "l":
            string = string.replace("l", "高")
        elif i == "L":
            string = string.replace("L", "金")
        elif i == "m":
            string = string.replace("m", "時")
        elif i == "M":
            string = string.replace("M", "手")
        elif i == "n":
            string = string.replace("n", "見")
        elif i == "N":
            string = string.replace("N", "市")
        elif i == "o":
            string = string.replace("o", "力")
        elif i == "O":
            string = string.replace("O", "米")
        elif i == "p":
            string = string.replace("p", "自")
        elif i == "P":
            string = string.replace("P", "前")
        elif i == "q":
            string = string.replace("q", "円")
        elif i == "Q":
            string = string.replace("Q", "合")
        elif i == "r":
            string = string.replace("r", "立")
        elif i == "R":
            string = string.replace("R", "内")
        elif i == "s":
            string = string.replace("s", "二")
        elif i == "S":
            string = string.replace("S", "事")
        elif i == "t":
            string = string.replace("t", "社")
        elif i == "T":
            string = string.replace("T", "者")
        elif i == "u":
            string = string.replace("u", "地")
        elif i == "U":
            string = string.replace("U", "京")
        elif i == "v":
            string = string.replace("v", "間")
        elif i == "V":
            string = string.replace("V", "田")
        elif i == "w":
            string = string.replace("w", "体")
        elif i == "W":
            string = string.replace("W", "学")
        elif i == "x":
            string = string.replace("x", "下")
        elif i == "X":
            string = string.replace("X", "目")
        elif i == "y":
            string = string.replace("y", "五")
        elif i == "Y":
            string = string.replace("Y", "後")
        elif i == "z":
            string = string.replace("z", "新")
        elif i == "Z":
            string = string.replace("Z", "明")
        elif i == "1":
            string = string.replace("1", "+")
        elif i == "2":
            string = string.replace("2", "_")
        elif i == "3":
            string = string.replace("3", "!")
        elif i == "4":
            string = string.replace("4", "@")
        elif i == "5":
            string = string.replace("5", "*")
        elif i == "6":
            string = string.replace("6", "&")
        elif i == "7":
            string = string.replace("7", "#")
        elif i == "8":
            string = string.replace("8", "$")
        elif i == "9":
            string = string.replace("9", "^")
        elif i == "0":
            string = string.replace("0", "?")
    return string